// Plan personalizado del usuario 'dake': rutina de 4 semanas (días A/B) + nutrición.
// Los ejercicios referencian los ids de la tabla `exercises` del catálogo de GymBro.

module.exports = {
  usuario: 'dake',
  objetivo: {
    principal: 'Perder grasa y ganar o mantener masa muscular',
    estrategia: 'Recomposición corporal',
    duracion_inicial: '4 semanas',
  },
  perfil: {
    edad: 29,
    peso_kg: 74,
    altura_cm: 179,
    entrenamientos_por_semana: 3,
    equipamiento: {
      mancuernas: 2,
      peso_maximo_por_mancuerna_kg: 12,
    },
  },
  rutina: {
    frecuencia: '3 días por semana',
    distribucion: 'Lunes, miércoles y viernes',
    duracion_aproximada_minutos: '45-60',
    intensidad: 'Normalmente 1-3 RIR',
    calentamiento: '5-8 minutos más 1-2 series ligeras del primer ejercicio',
    progresion: {
      prioridad: [
        'Aumentar repeticiones',
        'Aumentar dificultad',
        'Utilizar variantes unilaterales',
        'Usar tempo más lento',
        'Añadir pausas',
        'Aumentar series cuando corresponda',
      ],
      regla: 'Cuando se alcance el máximo de repeticiones con buena técnica y todavía exista margen, aumentar la dificultad',
    },
    dias_semana: [
      { dia: 'Lunes', tipo: 'A' },
      { dia: 'Miércoles', tipo: 'B' },
      { dia: 'Viernes', tipo: 'A' },
    ],
    semanas: [
      {
        semana: 1,
        objetivo: 'Establecer técnica y cargas',
        intensidad: '2-3 RIR',
        A: [
          { id: 31, series: 3, repeticiones: '8-12 por pierna', descanso_segundos: 120 },
          { id: 32, series: 3, repeticiones: '8-15', descanso_segundos: 120 },
          { id: 33, series: 3, repeticiones: '10-15 por lado', descanso_segundos: 90 },
          { id: 34, series: 3, repeticiones: '10-15', descanso_segundos: 120 },
          { id: 35, series: 2, repeticiones: '12-20', descanso_segundos: 60 },
          { id: 36, series: 2, repeticiones: '10-15', descanso_segundos: 75 },
          { id: 37, series: 2, repeticiones: '10-15', descanso_segundos: 75 },
        ],
        B: [
          { id: 38, series: 3, repeticiones: '10-15', descanso_segundos: 120 },
          { id: 39, series: 3, repeticiones: '8-15', descanso_segundos: 120 },
          { id: 40, series: 3, repeticiones: '10-15', descanso_segundos: 90 },
          { id: 41, series: 3, repeticiones: '10-20', descanso_segundos: 90 },
          { id: 9, series: 2, repeticiones: '10-15 por pierna', descanso_segundos: 90 },
          { id: 42, series: 2, repeticiones: '10-15', descanso_segundos: 75 },
          { id: 37, series: 2, repeticiones: '10-15', descanso_segundos: 75 },
        ],
      },
      {
        semana: 2,
        objetivo: 'Aumentar ligeramente el volumen y las repeticiones',
        intensidad: '1-3 RIR',
        cambios: [
          'Mantener los ejercicios de la semana 1',
          'Intentar aumentar repeticiones manteniendo técnica',
          'Añadir una serie a elevaciones laterales en Día A',
          'Añadir una serie de zancadas en Día B',
        ],
        A: [
          { id: 31, series: 3, repeticiones: '8-12 por pierna', descanso_segundos: 120 },
          { id: 32, series: 3, repeticiones: '8-15', descanso_segundos: 120 },
          { id: 33, series: 3, repeticiones: '10-15 por lado', descanso_segundos: 90 },
          { id: 34, series: 3, repeticiones: '10-15', descanso_segundos: 120 },
          { id: 35, series: 3, repeticiones: '12-20', descanso_segundos: 60 },
          { id: 36, series: 2, repeticiones: '10-15', descanso_segundos: 75 },
          { id: 37, series: 2, repeticiones: '10-15', descanso_segundos: 75 },
        ],
        B: [
          { id: 38, series: 3, repeticiones: '10-15', descanso_segundos: 120 },
          { id: 39, series: 3, repeticiones: '8-15', descanso_segundos: 120 },
          { id: 40, series: 3, repeticiones: '10-15', descanso_segundos: 90 },
          { id: 41, series: 3, repeticiones: '10-20', descanso_segundos: 90 },
          { id: 9, series: 3, repeticiones: '10-15 por pierna', descanso_segundos: 90 },
          { id: 42, series: 2, repeticiones: '10-15', descanso_segundos: 75 },
          { id: 37, series: 2, repeticiones: '10-15', descanso_segundos: 75 },
        ],
      },
      {
        semana: 3,
        objetivo: 'Intensificación',
        intensidad: '1-2 RIR',
        tempo_recomendado: '3 segundos bajada, 1 segundo pausa, subida controlada, especialmente en piernas',
        A: [
          { id: 31, series: 3, repeticiones: '8-12 por pierna', descanso_segundos: 120 },
          { id: 32, series: 4, repeticiones: '8-15', descanso_segundos: 120 },
          { id: 33, series: 4, repeticiones: '8-15 por lado', descanso_segundos: 90 },
          { id: 34, series: 3, repeticiones: '10-15', descanso_segundos: 120 },
          { id: 35, series: 3, repeticiones: '15-20', descanso_segundos: 60 },
          { id: 36, series: 2, repeticiones: '10-15', descanso_segundos: 75 },
          { id: 37, series: 2, repeticiones: '10-15', descanso_segundos: 75 },
        ],
        B: [
          { id: 38, series: 4, repeticiones: '10-20', descanso_segundos: 120 },
          { id: 39, series: 3, repeticiones: '8-15', descanso_segundos: 120 },
          { id: 40, series: 4, repeticiones: '8-15', descanso_segundos: 90 },
          { id: 41, series: 3, repeticiones: '12-20', descanso_segundos: 90 },
          { id: 9, series: 3, repeticiones: '10-15 por pierna', descanso_segundos: 90 },
          { id: 42, series: 2, repeticiones: '10-15', descanso_segundos: 75 },
          { id: 37, series: 2, repeticiones: '10-15', descanso_segundos: 75 },
        ],
      },
      {
        semana: 4,
        objetivo: 'Sobrecarga y consolidación',
        intensidad: '0-2 RIR en la última serie',
        nota: 'No es necesario llegar al fallo absoluto de forma habitual',
        A: [
          { id: 31, series: 3, repeticiones: '8-12 por pierna', descanso_segundos: 120 },
          { id: 32, series: 4, repeticiones: '8-15', descanso_segundos: 120 },
          { id: 33, series: 4, repeticiones: '8-15 por lado', descanso_segundos: 90 },
          { id: 34, series: 3, repeticiones: '10-15', descanso_segundos: 120 },
          { id: 35, series: 3, repeticiones: '15-20', descanso_segundos: 60 },
          { id: 36, series: 2, repeticiones: '10-15', descanso_segundos: 75 },
          { id: 37, series: 2, repeticiones: '10-15', descanso_segundos: 75 },
        ],
        B: [
          { id: 38, series: 4, repeticiones: '10-20', descanso_segundos: 120 },
          { id: 39, series: 3, repeticiones: '8-15', descanso_segundos: 120 },
          { id: 40, series: 4, repeticiones: '8-15', descanso_segundos: 90 },
          { id: 41, series: 3, repeticiones: '12-20', descanso_segundos: 90 },
          { id: 9, series: 3, repeticiones: '10-15 por pierna', descanso_segundos: 90 },
          { id: 42, series: 2, repeticiones: '10-15', descanso_segundos: 75 },
          { id: 37, series: 2, repeticiones: '10-15', descanso_segundos: 75 },
        ],
      },
    ],
    actividad_diaria: {
      pasos_objetivo: '7000-10000 diarios',
      cardio: 'Opcional; caminar es suficiente como base de actividad',
    },
  },
  nutricion: {
    calorias_objetivo_diarias_kcal: 2200,
    proteina_objetivo_diaria_g: '135-150',
    deficit_estimado_kcal: '200-300',
    ritmo_objetivo_perdida_peso_kg_semana: '0.2-0.4',
    principios: [
      'Priorizar alimentos mínimamente procesados',
      'Mantener proteína alta',
      'No es necesario eliminar carbohidratos',
      'No son necesarios suplementos',
      'Ajustar calorías según evolución durante 2-3 semanas',
    ],
    dieta_7_dias: [
      { dia: 1, etiqueta: 'Lunes',
        desayuno: '60 g avena + 250 ml leche + 1 plátano + 2 huevos',
        comida: '150-180 g pollo + 80-90 g arroz + 200 g verduras + 10 g aceite de oliva',
        snack: '200-250 g yogur griego alto en proteína + fruta',
        cena: '200 g merluza + 350 g patata + ensalada + 15 g aceite de oliva',
        kcal: 2200, proteina: 145 },
      { dia: 2, etiqueta: 'Martes',
        desayuno: '3 huevos + 80 g pan + 1 pieza de fruta',
        comida: '80-90 g pasta + 150 g carne picada magra + 150 g tomate triturado + 10 g aceite de oliva',
        snack: '200-250 g yogur griego alto en proteína + fruta + 20-30 g avena',
        cena: '170 g pollo + 350 g patata + 200 g verduras + 10 g aceite de oliva',
        kcal: 2200, proteina: 150 },
      { dia: 3, etiqueta: 'Miércoles',
        desayuno: '60 g avena + 200-250 g yogur + 1 plátano + 10 g crema de cacahuete',
        comida: '150-180 g pollo + 80-90 g arroz + 200 g verduras + 10 g aceite de oliva',
        snack: '2 huevos + fruta',
        cena: '170 g salmón + 300 g patata + verduras',
        kcal: 2250, proteina: 140 },
      { dia: 4, etiqueta: 'Jueves',
        desayuno: '3 huevos + 80 g pan + 1 pieza de fruta',
        comida: '90 g pasta + 1-2 latas de atún al natural + 150 g tomate triturado + 10 g aceite de oliva',
        snack: '200-250 g yogur griego alto en proteína + 1 plátano',
        cena: '150-180 g pollo + 80-90 g arroz + 200 g verduras + 10 g aceite de oliva',
        kcal: 2150, proteina: 150 },
      { dia: 5, etiqueta: 'Viernes',
        desayuno: '60 g avena + 250 ml leche + 1 plátano + 2 huevos',
        comida: '170 g pollo + 350 g patata + 200 g verduras + 10 g aceite de oliva',
        snack: '200-250 g yogur griego alto en proteína + fruta',
        cena: '200 g merluza + 80-90 g arroz + 200 g verduras + 15 g aceite de oliva',
        kcal: 2200, proteina: 145 },
      { dia: 6, etiqueta: 'Sábado',
        desayuno: '3 huevos + 80 g pan + 1 pieza de fruta',
        comida: '150 g carne picada magra + 80-90 g arroz + 200 g verduras + 10 g aceite de oliva',
        snack: '200-250 g yogur griego alto en proteína + 20-30 g avena + fruta',
        cena: '170 g pollo + 350 g patata + ensalada + 10 g aceite de oliva',
        kcal: 2250, proteina: 150 },
      { dia: 7, etiqueta: 'Domingo',
        desayuno: '60 g avena + 200-250 g yogur + 1 plátano + 10 g crema de cacahuete',
        comida: '150-180 g pollo + 80-90 g pasta + 150 g tomate triturado + 10 g aceite de oliva',
        snack: '2 huevos + fruta',
        cena: '170 g salmón + 300 g patata + verduras',
        kcal: 2200, proteina: 140 },
    ],
    nota_pesos: 'Arroz, pasta y avena se indican en peso en crudo',
    lista_compra_semanal: {
      proteinas: [
        '1.2-1.4 kg de pechuga de pollo',
        '400 g de merluza',
        '350 g de salmón',
        '300 g de carne picada magra',
        '2-3 latas de atún al natural',
        '18 huevos',
        '1.5-2 kg de yogur griego alto en proteína',
        '2 litros de leche',
      ],
      carbohidratos: [
        '500 g de avena',
        '500 g de arroz',
        '500 g de pasta',
        '2.5 kg de patatas',
        '500 g de pan',
        '7 plátanos',
        '7-10 piezas de otras frutas',
      ],
      verduras: [
        '1.5-2 kg de verduras variadas',
        '2-3 bricks o latas de tomate triturado',
        '2 bolsas de ensalada',
      ],
      grasas: [
        'Aceite de oliva virgen extra',
        'Crema de cacahuete',
        '150-200 g de frutos secos',
      ],
    },
    preparacion_comidas: {
      tiempo_maximo_por_cocinado_minutos: 30,
      estrategia: 'Batch cooking dos veces por semana',
      domingo: [
        'Preparar 600-700 g de pollo',
        'Preparar aproximadamente 300 g de arroz',
        'Preparar aproximadamente 1 kg de patata',
        'Preparar verduras',
      ],
      miercoles: [
        'Repetir la preparación',
        'Conservar las raciones preparadas adecuadamente refrigeradas',
      ],
    },
    seguimiento: {
      peso: 'Pesarse 3-7 mañanas por semana y utilizar la media semanal',
      cintura: 'Medir una vez por semana',
      fotos: 'Cada 2-4 semanas',
      entrenamiento: 'Registrar peso, repeticiones y RIR',
      ajustes: {
        perdida_esperada: '0.2-0.4 kg por semana',
        si_no_hay_perdida_durante_2_3_semanas: 'Reducir aproximadamente 150-200 kcal/día o aumentar actividad',
        si_se_pierde_mas_de_0.5kg_semana_y_baja_el_rendimiento: 'Añadir aproximadamente 100-200 kcal/día',
        proteina: 'Mantener aproximadamente 135-150 g/día',
      },
    },
    suplementos: {
      necesarios: false,
      recomendacion: 'No son necesarios para alcanzar el objetivo',
    },
  },
};
